/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModirRouteImport } from './routes/modir'
import { Route as ApiClubRouteImport } from './routes/api/club'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModirRoute = ModirRouteImport.update({
  id: '/modir',
  path: '/modir',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClubRoute = ApiClubRouteImport.update({
  id: '/api/club',
  path: '/api/club',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/modir': typeof ModirRoute
  '/api/club': typeof ApiClubRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/modir': typeof ModirRoute
  '/api/club': typeof ApiClubRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/modir': typeof ModirRoute
  '/api/club': typeof ApiClubRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/modir' | '/api/club'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/modir' | '/api/club'
  id: '__root__' | '/' | '/modir' | '/api/club'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModirRoute: typeof ModirRoute
  ApiClubRoute: typeof ApiClubRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modir': {
      id: '/modir'
      path: '/modir'
      fullPath: '/modir'
      preLoaderRoute: typeof ModirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/club': {
      id: '/api/club'
      path: '/api/club'
      fullPath: '/api/club'
      preLoaderRoute: typeof ApiClubRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModirRoute: ModirRoute,
  ApiClubRoute: ApiClubRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
